---
title: "earthquake_analysis"
output: html_document
---


```{r}

library(ggmap)
library(dplyr)
library(httr)
library(XML)
library(stringr)
library(lubridate)

```

## Downloading and processing data

```{r}

# Download entire earthquake data from 2014 for Germany
page <- GET('http://www.seismologie.bgr.de/cgi-bin/eisy_test_iframe.pl?begin_date=20140101&end_date=20140713&min_lat=&max_lat=&min_lon=&max_lon=&min_mag=&max_mag=&')
page_content <- content(page, 'text')

parsed_content <- xmlRoot(htmlParse(page_content))
doc <- xpathSApply(parsed_content, '//pre', xmlValue)
head(doc)

data <- doc[-1]

date <- str_sub(data, 1, 10) 
time <- str_sub(data, 11, 17) %>% str_trim 
lat <- str_sub(data, 18, 25) %>% str_trim 
long <- str_sub(data, 26, 32) %>% str_trim 
mag <- str_sub(data, 33, 38) %>% str_trim 
region <- str_sub(data, 39, str_length(data)) %>% str_trim

processed_data <- data.frame(date, time, lat, long, mag, region, 
                             stringsAsFactors = FALSE)

# Only include earthquakes around Darmstadt and change order so that older
# earthquakes will get plotted at first
processed_data <- filter(processed_data, grepl('.*Darmstadt.*', region)) %>%
  transform(
    date  = dmy(date),
    lat   = as.numeric(lat),
    long  = as.numeric(long),
    mag   = as.numeric(mag)
    ) %>%
  arrange(date)

```


## Plotting data

```{r}

# Get map of Darmstadt
da_toner <- get_map('Darmstadt', maptype = 'toner', source = 'stamen')

# Create base layer for plotting
gg <- ggmap(da_toner)

# Add earthquake data to the plot
gg + geom_point(aes(x = long, y = lat, fill = mag, size = mag), processed_data)


```

